### ISSUE TITLE
Can't stop swipe for inside range input

### ISSUE THREAD

**Issue by avishwakarma** [voronianski/react-swipe#65]
Hi,

I have a range input in one on the swipe page, which user can slide from left to right to increase decrease values. Due to the swipe component as a parent component when someone try to slide the range input, page get swiped.

I have tried the `disableScroll={true}` on the range input component but issue is still the same.

Can anyone please help to find a way to stop the swip if event occur or certain inside elements.

**Comment by voronianski** [comment]
@akvlko please update issue regarding https://github.com/voronianski/react-swipe/blob/gh-pages/.github/ISSUE_TEMPLATE.md and feel free to reopen it then.

**Comment by realbugger** [comment]
I don't see a solution here, though this issue is closed. I too would love to see a way to stop or disable the swipable area. This is particularly useful when there are other swipable controls inside a reac-swipe component. I've trying `start: () => false` but it doesn't really stop the swiping movement.
