### ISSUE TITLE
render 2 items into 4

### ISSUE THREAD

**Issue by iamusenix** [voronianski/react-swipe#80]
## Description

I used this for a photo lightbox. Weird things happened when I put 2 photos in this component. 
1, 2+ are working fine. ONLY 2 photos will be duplicated into 4(repeat one time).

**Comment by Mr-Taco** [comment]
this happens to account for continuous navigations between slides. only for the case of two slides, a duplicate slide will be created for each. to solve, do not use continuous. 

react does not like this feature of swipe.js, since react issues unique ids for each DOM node. since swipe.js literally duplicates the DOM node, react will throw a warning about having two identical nodes with different react ids.

**Comment by iamusenix** [comment]
@PhilipBrady13 Thanks for your response. I solved this problem by duplicate my react elements before swipe.js takes over. Hope this will help someone who might encounter the same problem. :)

**Comment by voronianski** [comment]
@iamusenix @PhilipBrady13 this issue can be added to README into somekind of "Known issues" paragraph.

**Comment by qiaolevip** [comment]
It seems not solved yet, hope solved it notice @me.

I do it bad solution in js when I use my Bullets Component;

```
attractBullet(index) {
    const size = this.props.items.length;
    if (size == 2) index = index % 2;
    this.setState({curIndex: index});
  }
```

**Comment by jackple** [comment]
I use this way to resolve the problem:
//set pagation:
const index = index > data.length - 1 ? index - data.length : index;
this.setState({
      currentIndex: index
})
//click
data[this.state.currentIndex];

**Comment by jackple** [comment]
I use this way to resolve the problem:
//set pagation:
const index = index > data.length - 1 ? index - data.length : index;
this.setState({
      currentIndex: index
})
//click
data[this.state.currentIndex];

**Comment by amnaaskari** [comment]
what is the suggested solution for this? changing continuous to true didn't help
